### ISSUE TITLE
There should be a `CONTRIBUTING.md` or pull request template explaining unusual requirements in advance

### ISSUE THREAD

**Issue by daniel-beck** [jenkins-infra/jenkins-io-components#105]
> We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

There should be a `CONTRIBUTING.md` or pull request template explaining unusual requirements in advance.

_Originally posted by @daniel-beck in https://github.com/jenkins-infra/jenkins-io-components/issues/104#issuecomment-1729871258_

**Comment by KitsuneKode** [comment]
@halkeye  this issue seems to be resolved

**Comment by KitsuneKode** [comment]
@halkeye  This issue seems to be resolved.
 
should add a reference of the contribution.md file in the readme
