### ISSUE TITLE
Add Contributor Spotlight link to header & footer

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/jenkins-io-components#113]
### What feature do you want to see added?

As of today (November 28) the [Jenkins Contributor Spotlight](https://contributors.jenkins.io/) site is now live. 

Would it be possible to add this link to the header as its own item titled Contributor Spotlight? It could go between "Success Stories" and "Documentation".
For the footer, could it be added under the Community column?

The [contributor spotlight repo](https://github.com/jenkins-infra/contributor-spotlight) has been updated accordingly and should have everything needed for inclusion.

**Comment by alyssat** [comment]
+1 for it to go between "Success Stories" and "Documentation"

**Comment by halkeye** [comment]
https://github.com/jenkins-infra/jenkins-io-components/pull/114
