### ISSUE TITLE
Update code of conduct URL

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/jenkins-io-components#132]
The code of conduct URL in the footer points to https://www.jenkins.io/conduct/, which redirects to https://www.jenkins.io/project/conduct/. Rather than relying on a redirect, we should use the location direction right away.

**Comment by halkeye** [comment]
Do you mean https://github.com/jenkins-infra/jenkins-io-components/blob/7e4142f87b4f5b72f380e4cd5e47b9501bae56d2/src/jio-navbar.ts#L181 or something in this github settings?

**Comment by NotMyFault** [comment]
I was referring to the code, because clicking on the "Code of Conduct" URL at the bottom of https://www.jenkins.io/ takes me to https://www.jenkins.io/conduct/ rather than https://www.jenkins.io/project/conduct/

**Comment by nouralmulhem** [comment]
I can have this
