### ISSUE TITLE
Add link to Jenkins Infra Stats site on the Navbar / Footer

### ISSUE THREAD

**Issue by shlomomdahan** [jenkins-infra/jenkins-io-components#147]
### What feature do you want to see added?

As part of my GSoC project, I've been working on a revamped Jenkins Infra Stats site. You can check out the [New Site](https://new.stats.jenkins.io) and compare it with the [Old Site](https://stats.jenkins.io).

Given that the site uses the Jio navbar and footer components, my mentoring team suggested including a link to the site (stats.jenkins.io) in either the header or footer.

Could you please advise on the optimal location for this link?

ref:
- https://github.com/jenkins-infra/stats.jenkins.io/issues/88

**Comment by MarkEWaite** [comment]
I think that it should be placed in the footer under the "Project" heading   The statistics are of interest to project leaders but not as much of interest to project users.  I think the header should be reserved for items that are focused on project users.

**Comment by shlomomdahan** [comment]
@MarkEWaite

Thank you for your feedback. I agree that placing the statistics under the "Project" heading in the footer would better serve our project leaders. I will open a PR to implement this change.
