### ISSUE TITLE
The nav having extra heading and it's not sticky

### ISSUE THREAD

**Issue by Mahmoudgalalz** [jenkins-infra/jenkins-io-components#80]
Hello, I'm a potential GSoC student, I'm working on a demo and I'm using those components

the nav has extra space, I can work on it
@halkeye @krisstern

![image](https://user-images.githubusercontent.com/42272376/226500436-6795c4ad-24e6-499e-8033-11e3a242a34c.png)

**Comment by halkeye** [comment]
The component shouldn't decide how and where it is on the page.

**Comment by Mahmoudgalalz** [comment]
I just removed all the CSS, that will affect the nav, I will check again, I have explored the component, and yeah you are right but Its getting me confused :laughing:

**Comment by halkeye** [comment]
The most basic fixed top (as seen on accounts.jenkins.io) is 
```
.fixed-top {
  position: fixed;
  top: 0;
  right: 0;
  left: 0;
  z-index: 1030;
}
```

None of the other sites have it sticky.

**Comment by Mahmoudgalalz** [comment]
Thanks, I will use them instead to force the ui, and see, I will be back to you
