### ISSUE TITLE
Footer is not fixed to bottom

### ISSUE THREAD

**Issue by Mahmoudgalalz** [jenkins-infra/jenkins-io-components#89]
This issue comes from https://github.com/jenkins-infra/jenkins.io/issues/6248

I created a solution for it but just for the main site

and the solution made a bad effect on other websites like the Account app

so we need to do a general solution
@halkeye so it's recommended to make a general fix to the component here, or just fix it for both websites?

**Comment by halkeye** [comment]
components shouldn't control where the controlling page renders them. 

from the components point of view, you can have 20 of them, it doens't care.

jenkins.io should fix it to the bottom.

**Comment by Mahmoudgalalz** [comment]
so I think it is better to work on these for both sites
